import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Flowbite React",
  description: "Generated by create flowbite react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* TODO: */}
      {/* For some reason the ThemeModeScript is causing a error on the browser */}
      <head></head>
      <body className={inter.className}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
